spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javaweb
    username: sa
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: classpath:static/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springboot.pojo

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
