
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javaweb
    username: sa
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: classpath:static/

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #输出日志
server:
  port: 8443
